# Generated by Django 5.0.4 on 2024-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
