# Generated by Django 5.0.4 on 2024-05-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='check_in_date',
            field=models.DateField(null=True),
        ),
    ]
