# Generated by Django 5.0.4 on 2024-07-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_remove_maintenancerequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='student',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
