# Generated by Django 5.0.5 on 2024-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_requests'),
        ),
    ]
