# Generated by Django 5.0.4 on 2024-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_maintenancerequest_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bursary_contact_information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bursary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bursary_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bursary_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
