# Generated by Django 5.0.4 on 2024-05-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_payment_bursary_contact_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='accommodations.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='ensuite_additional_rent',
            field=models.DecimalField(decimal_places=2, default=800.0, max_digits=10),
        ),
    ]
