# Generated by Django 5.0.4 on 2024-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_building_rent_amount_rentalagreement_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=3800.0, max_digits=10),
        ),
    ]
