# Generated by Django 5.0.4 on 2024-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0009_remove_payment_rental_agreement_leaseagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
