# Generated by Django 5.0.4 on 2024-05-08 05:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27 70 0000 000'. 10 digits allowed.", regex='^\\+?\\d{9,15}$')])),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('confirmation_token', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('course', models.CharField(default='Unknown', max_length=100)),
                ('sponsor_details', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_identification', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
