# Generated by Django 5.0.4 on 2024-05-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirmation_token',
        ),
    ]
